### ISSUE TITLE
generating a new structure from Fragalysis

### ISSUE THREAD

**Issue by Sharifahsabrina** [StructuralGenomicsConsortium/CNP24-NSP10_14-Frags#3]
Below I've proposed and created a few molecules that are based on overlapping fragments on Fragalysis. We have chosen to employ Lipinski's rule of five and rule of three to gauge the efficacy of these proposed molecules and fragments. 
![image](https://github.com/StructuralGenomicsConsortium/CNP24-NSP10_14-Frags/assets/147885971/4c8f6bd8-9a11-4b51-9d88-dae0fd46c701)

![image](https://github.com/StructuralGenomicsConsortium/CNP24-NSP10_14-Frags/assets/147885971/cb35eb01-2710-47ef-86f4-f1028d99ec66)

![image](https://github.com/StructuralGenomicsConsortium/CNP24-NSP10_14-Frags/assets/147885971/063362ca-220f-4899-8f59-e5f864423a40)

**Comment by mattodd** [comment]
Closing because we are clarifying that the request is for molecules that are commercially available, or trivial to synthesise.
These designs are available in @Sharifahsabrina 's thesis [here](https://github.com/StructuralGenomicsConsortium/CNP24-NSP10_14-Frags/blob/main/Reports%20and%20Theses/2024/UCL%20Sabrina%20MPharm%20Project%202024.pdf).
